#**NumPy Assignment**

##1) How to Creating a 3x3 Identity Matrix with Float Data Type?


In [ ]:
import numpy as np
data = np.arange(9.0).reshape(3,3)
data

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

##2) Create a 1D Array with Random Values between 0 and 1.


In [ ]:
data=np.random.random(10)
data

array([0.42381616, 0.7541934 , 0.8399574 , 0.40920975, 0.73663129,
       0.82713102, 0.32714859, 0.6868585 , 0.46610685, 0.06186342])

## 3) Create a 2D Array with Random Integer Values.


In [ ]:
np.random.randint(0,12,size=(4,5))

array([[ 1, 11,  2,  1,  8],
       [ 0, 10,  5,  4,  6],
       [11,  8,  5,  1,  4],
       [ 9,  3,  6,  8,  2]])

## 4) Creating an Array Using a Custom Function

In [ ]:
def create_Array(a,b):
  B = np.arange(a,b)
  return B

input_A = int(input("starting point :"))
input_b = int(input("ending point:- "))

create_Array(input_A,input_b)


starting point :1
ending point:- 5


array([1, 2, 3, 4])

## 5) Reshaping a 1D Array into a 2D Array


In [ ]:
oneD_array = np.arange(6)
oneD_array

Two_D_Array_convert = oneD_array.reshape(2,3)
Two_D_Array_convert

array([[0, 1, 2],
       [3, 4, 5]])

## 6) How to Creating a 3x3 Array of Ones?


In [ ]:
Three_by_Three = np.ones(9).reshape(3,3)
Three_by_Three

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 7)  How to get the common items between two pythons NumPy?

In [ ]:
a = np. array ([1,2,3,2,3,4,3,4,5,6])
b = np. array ([7,2,10,2,7,4,9,4,9,8])

Intersect = np.intersect1d(a,b)
Intersect

array([2, 4])

## 8) From array a remove all items present in array b

In [ ]:
a = np. array ([1,2,3,4,5])
b = np. array ([5,6,7,8,9])

result = np.setdiff1d(a,b)
result

array([1, 2, 3, 4])

## 9. Limit the number of items printed in python NumPy array a to a maximum of 6 elements.


In [ ]:
a = np. arange (15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

## 10) Drop all nan values from a 1D NumPy

In [ ]:
Np=np.array ([1,2,3, np.nan,5,6,7, np.nan])

clean_array = Np[~np.isnan(Np)]
clean_array


array([1., 2., 3., 5., 6., 7.])

## 11) Question: Create a 1D NumPy array of the first 20 natural numbers and a 2D NumPy array of shape (4, 5) with values ranging from 1 to 20.


In [ ]:
q1 = np.arange(1,21)
q1 # 1D array

final_resullt = q1.reshape(4,5)
final_resullt

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## 12) Given a 3D NumPy array of shape (2, 3, 4), find its shape, size,number of dimensions, and data type. Change its data type to float64 and verify the change.


In [ ]:
array_3d = np.random.randint(1, 101, size=(2, 3, 4))
array_3d

# find its shape, size, number of dimensions, and data type
print("\nShape of array:", array_3d.shape)
print("Size of array (total elements):", array_3d.size)
print("Number of dimensions:", array_3d.ndim)
print("Data type before conversion:", array_3d.dtype)


Shape of array: (2, 3, 4)
Size of array (total elements): 24
Number of dimensions: 3
Data type before conversion: int64


## 13) Reshape a 1D array of 12 elements into a 3x4 2D array and then flatten it back into a 1D array using ravel (). Verify that the flattened array matches the original.


In [ ]:
d1 = np.arange(1,13)
d1 # 1d array

#reshape it into 3 x 4
d2 = d1.reshape(3,4)

#use ravel to flatten 2d array into 1d :-
d1 = d2.ravel()
d1

array([ 1,  2,  3, ..., 10, 11, 12])

## 14) Given two arrays, a = np. array ([1, 2, 3]) and b = np. array ([4,5, 6]), perform element-wise addition, subtraction, multiplication, and division. Explain the behavior when dividing by zero.

In [ ]:
a = np. array ([1, 2, 3])
b = np. array ([4,5, 6])
a,b
print(a+b)
print(a-b)
print(a*b)
print(a//b) ## bcz when we use floor divison they consider smallests value from the result

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0 0 0]


## 15) Create a 2D array of shape (3, 1) and a 1D array of length 3. Perform element-wise addition using broadcasting. Explain how broadcasting rules apply in this scenario.


In [ ]:
a = np.arange(1,4).reshape(3,1)
b=np.array([12,24,23])
a,b
#print("B :- ", b)
print(a)
print(b)
print()
print()
print(a+b)



[[1]
 [2]
 [3]]
[12 24 23]


[[13 25 24]
 [14 26 25]
 [15 27 26]]


## 16) Question: Generate a random 2D array of integers between 0 and 10. Useconditional operators to create a Boolean mask identifying elements greater than 5. Replace all elements greater than 5 with the value 5.


In [ ]:
import numpy as np


array_2d = np.random.randint(0, 11, size=(4, 5))
print("Original Array:\n", array_2d)

mask = array_2d > 5
print("\nBoolean Mask (Elements > 5):\n", mask)


array_2d[mask] = 5
print("\nArray After Replacement:\n", array_2d)


Original Array:
 [[ 9  6  0  5  9]
 [ 6  1  4  3 10]
 [ 1  5  8  3  2]
 [ 1  0  5  3  2]]

Boolean Mask (Elements > 5):
 [[ True  True False False  True]
 [ True False False False  True]
 [False False  True False False]
 [False False False False False]]

Array After Replacement:
 [[5 5 0 5 5]
 [5 1 4 3 5]
 [1 5 5 3 2]
 [1 0 5 3 2]]


##17) Given a 4x4 array of random integers, use indexing and slicing to extract:


1.   The entire second row
2.   The last column
3.   The subarray consisting of the first two rows and first two columns


In [ ]:
array = np.arange(16).reshape(4,4)
print(array)

# The entire secone row
esr = array[1:2:,::]
print(esr)

# The last column
lc = array[::,3::]
print(lc)

# The subarray consisting of the first two rows and first two columns
subarray =  array[:2,:2]
subarray

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[4 5 6 7]]
[[ 3]
 [ 7]
 [11]
 [15]]


array([[0, 1],
       [4, 5]])

## 19) Create a random 4x4 matrix and use NumPy to compute its eigenvalues and eigenvectors. Verify the eigenvalues by reconstructing the matrix.


In [ ]:
import numpy as np
array_2d = np.random.randint(0, 17, size=(4, 4))
array_2d

array([[ 6,  7,  3,  4],
       [ 2,  9,  6, 10],
       [ 5,  0,  0,  0],
       [ 9, 14,  9,  6]])

## 20) Create a 1D array of 27 elements and reshape it into a 3x3x3 3D array. Flatten it back into a 1D array and compare the flattened array with the original.


In [ ]:
one_d_array = np.arange(0,27)
print(one_d_array)

d = one_d_array.reshape(3,3,3)
print(d)

d= d.flatten()
d

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## 21) : Perform matrix multiplication of two 2D arrays using np.dot () and @. Compare the results and performance of both methods using a large dataset.


In [ ]:
a = np.arange(4).reshape(2,2)
b = np.arange(5,9).reshape(2,2)

print(a)
print()
print(b)
print()
c = np.dot(a,b)
print(c)

d=a@b
d



[[0 1]
 [2 3]]

[[5 6]
 [7 8]]

[[ 7  8]
 [31 36]]


array([[ 7,  8],
       [31, 36]])

## 22) Create a 3D array of shape (2, 1, 4) and a 2D array of shape (4,1). Perform an element-wise operation using broadcasting and explain the result. Use np. new axis to achieve the same result without broadcasting.

In [ ]:
import numpy as np


array_3d = np.array([[[1, 2, 3, 4]],
                      [[5, 6, 7, 8]]])


array_2d = np.array([[10],
                      [20],
                      [30],
                      [40]])
result_broadcasting = array_3d + array_2d.T


array_2d_reshaped = array_2d.T[:, np.newaxis, :]
result_no_broadcasting = array_3d + array_2d_reshaped


print("3D Array (2,1,4):\n", array_3d)
print("\n2D Array (4,1):\n", array_2d)

print("\nResult using Broadcasting:\n", result_broadcasting)
print("\nResult using np.newaxis:\n", result_no_broadcasting)


3D Array (2,1,4):
 [[[1 2 3 4]]

 [[5 6 7 8]]]

2D Array (4,1):
 [[10]
 [20]
 [30]
 [40]]

Result using Broadcasting:
 [[[11 22 33 44]]

 [[15 26 37 48]]]

Result using np.newaxis:
 [[[11 22 33 44]]

 [[15 26 37 48]]]


## 23) Generate a 2D array of random floats between 0 and 1. Use conditional operators to create a Boolean mask for values less than 0.5. Replace these values with their squares and leave the rest unchanged.

In [ ]:
a = np.random.rand(9).reshape(3,3)
print(a)

print()

b = a <0.5
print(b)
print()


a[b] = 0.5*0.5
print(a)



[[0.2357541  0.59391649 0.98764306]
 [0.37573002 0.06453595 0.24840824]
 [0.36494015 0.32746714 0.62051595]]

[[ True False False]
 [ True  True  True]
 [ True  True False]]

[[0.25       0.59391649 0.98764306]
 [0.25       0.25       0.25      ]
 [0.25       0.25       0.62051595]]


## 24) : Given a 5x5 array of sequential integers, use slicing to:
### Extract the diagonal elements
### Replace the elements of the middle row with zeros
### Flip the array vertically and horizontally


In [ ]:
a = np.arange(1,26).reshape(5,5)
print(a)
print()
#1np
print(a[range(5),range(5)])
print()
#2
a[2:3,:] = 0
print(a)

#3
print()
print(a[::-1,:])
print()
print(a[:,::-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[ 1  7 13 19 25]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 0  0  0  0  0]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[[21 22 23 24 25]
 [16 17 18 19 20]
 [ 0  0  0  0  0]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [ 0  0  0  0  0]
 [20 19 18 17 16]
 [25 24 23 22 21]]


## 25) : Create a 4D array of shape (2, 3, 4, 5) with random integers. Use advanced slicing to extract a subarray and compute the mean along a specified axis.


In [ ]:
a = np.random.randint(0, 100, size=(2, 3, 4, 5))

print("4D Array of Shape (2, 3, 4, 5) with Random Integers:\n", a)

subarray = a[0, 1:3, 0:2, :]
print("\n",subarray)

mean_result = np.mean(subarray, axis=2)
print("\n",mean_result)

4D Array of Shape (2, 3, 4, 5) with Random Integers:
 [[[[ 1 66 36  6 91]
   [85  2  5 81 60]
   [10 85 57 44 11]
   [30 73 12 70 61]]

  [[39 64 89 83  6]
   [22 23 24 75 73]
   [91 62 21 24 77]
   [86 47 85 65 14]]

  [[63 97 35 49 64]
   [36 64 12 17 79]
   [89 10 55 31 87]
   [71  2 65 17 24]]]


 [[[ 3  5  0 18 27]
   [79 48 24 50 28]
   [35 20 45 41 81]
   [96 44 30  2 96]]

  [[68 63 62 90 62]
   [18 84 40 48 19]
   [47 95 48 61 93]
   [75 97 64 43 33]]

  [[86 47  6 64 73]
   [64  8 46 20 62]
   [29 59 61 47 38]
   [74 84 52 97 27]]]]

 [[[39 64 89 83  6]
  [22 23 24 75 73]]

 [[63 97 35 49 64]
  [36 64 12 17 79]]]

 [[56.2 43.4]
 [61.6 41.6]]


## 26) Given an array of shape (10, 20), reshape it to (20, 10) and (5,40). Discuss the impact on the array's shape, size, and dimensionality.


In [ ]:
a = np.arange(200).reshape(10,20)
a

a2 = a.reshape(20,10)
a2

a3 = a.reshape(5,40)
a3

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
        106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
        119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145,
        146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158,
        159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 

## 27) Generate a large 2D array and demonstrate the use of np. reshape () and unravel () to manipulate its shape for various linear algebra operations.


In [ ]:
import numpy as np

a = np.arange(4).reshape(2,2)
a

a.ravel()

array([0, 1, 2, 3])

## 28)  Given a 6x6 matrix, use advanced indexing and slicing to extract the upper triangular part of the matrix and set the lower triangular part to zero.Verify the result.

In [14]:
a = np.random.randint(36,size=(6,6))

for i in range(1, 6):
    a[i, :i] = 0

a


array([[30, 12, 27,  7, 21, 16],
       [ 0, 25, 24, 13,  3, 14],
       [ 0,  0, 26,  6,  8,  3],
       [ 0,  0,  0, 32, 13, 13],
       [ 0,  0,  0,  0, 24,  9],
       [ 0,  0,  0,  0,  0,  8]])